### ISSUE TITLE
Daten Projektplanung

### ISSUE THREAD

**Issue by FranzKorf** [fabiansch/esep_sortingmachine#1]
Guten Morgen Herr Schicke, das Thema Projektplanung und somit  Aspekte wie Ganttdiagramme wird erst nächste Woche Freitag in der VL von Zhen Dai behandelt. Damit brauchen Sie am Dienstag die gestern angesprochenen Sachen zur Projektplanung natürlich nicht liefern. Sie verschieben sich auf den dritten ESEP Termin.

Liebe Grüße Franz K.

**Comment by fabiansch** [comment]
vielen Dank. :)
