### ISSUE TITLE
implement observer pattern

### ISSUE THREAD

**Issue by fabiansch** [fabiansch/esep_sortingmachine#37]
LogicLayer inherits Observer
HAL inherits Subject

**Comment by fabiansch** [comment]
work gets done on branch [observer_pattern](fabiansch/esep_sortingmachine/tree/observer_pattern)

**Comment by fabiansch** [comment]
@RobertPalmHawHH das komische Verhalten vorhin mit der HardwareLayer im Konstruktor von Subject liegt sicher daran, dass wir vergessen haben, dass HardwareLayer von Subject **public** erbt.

also irgendwie sowas:

```cpp
class HardwareLayer : public Subject // do not forget to inherit public
```

**Comment by RobertPalmHawHH** [comment]
ready for merge

**Comment by fabiansch** [comment]
pull request #43 gestellt. Damit ist das Ticket DONE
