### ISSUE TITLE
Höhensensor Grundfunktionalität implementieren

### ISSUE THREAD

**Issue by fabiansch** [fabiansch/esep_sortingmachine#38]
BeispielCode vom Tutorium!

Sensor soll Messung starten können.
Sensor soll warten und überprüfen, ob Messwert da ist. Wenn nicht, noch einmal etwas warten.
Sensor soll Messwert lesen und in einen Speicherbereich schreiben, der mit einem Mutex versehen ist. Danach soll eine Message in den Messagebuffer geschrieben werden und ein notifyObservers() aufgerufen werden.

**Comment by fabiansch** [comment]
Kann bearbeitet werden wenn Observer Pattern implementiert wurde

**Comment by maltejanssen** [comment]
done in #50
