### ISSUE TITLE
MS Software

### ISSUE THREAD

**Issue by FranzKorf** [fabiansch/esep_sortingmachine#44]
@fabiansch Guten Abend Zusammen, unter Release und Tags finde ich keinen Eintrag. Suche ich an der falschen Stelle oder fehlt ein entsprechender Tag / Release?

Mit freundlichen Grüßen

   Franz K.

**Comment by fabiansch** [comment]
ja der release-tag fehlt. Mein Vorschlag:
wir arbeiten die von Ihnen genannten Anmerkungen in #45 (Kommentare zum Code) ein und pushen das dann mit einem Releasetag "Milestone_02".

Was meinen Sie?

Freundliche Grüße,
Fabian
