### ISSUE TITLE
Kommentare zum Code

### ISSUE THREAD

**Issue by FranzKorf** [fabiansch/esep_sortingmachine#45]
Guten Abend Zusammen,

hier einige Kommentare zum Code:

- Die Structure Signal ist erstmal schwer verständlich ohne jegliche Kommentare. Wo kann ich diese finden? In Summe ist der Code nicht dokumentiert - das muss nachgezogen werden.

- Der Code wird erstmal ohne viele Schnörkel und sehr schlank. Wenn ich das richtig sehe, ist das auch ein Ziel in diesem Jahr. Ein einfache Code, der in eine frühen Phase läuft.

- Ich habe nahezu keine Fehlerbehandlung gefunden. Das muss nochgezogen werden. Ein typischen Beispiel ist die fehlende Fehlerbehandlung bei ThreadCtl.

- Wo finde ich Klassendiagramme etc.

- Wie sieht es in Sachen Sensoren aus?

- Haben Sie schon die Architektur für die grundlegende Kommunikation festgelegt?

Schönen Abend 

	Franz K.

**Comment by fabiansch** [comment]
Guten Tag Herr Korf,

vielen Dank für die Anmerkungen.

> Die Structure Signal ist erstmal schwer verständlich ohne jegliche Kommentare. Wo kann ich diese finden? In Summe ist der Code nicht dokumentiert - das muss nachgezogen werden.

Das ziehen wir nach und steht bis Dienstag. Adressiert mit Issue #46.

> Der Code wird erstmal ohne viele Schnörkel und sehr schlank. Wenn ich das richtig sehe, ist das auch ein Ziel in diesem Jahr. Ein einfache Code, der in eine frühen Phase läuft.

Vielen Dank und ja unser Ziel ist es Code zu schreiben, der leicht verständlich und dabei flexibel bleibt. 

> Ich habe nahezu keine Fehlerbehandlung gefunden. Das muss nochgezogen werden. Ein typischen Beispiel ist die fehlende Fehlerbehandlung bei ThreadCtl.

Das ziehen wir ebenfalls nach. Adressiert mit Issue #47.

> Wo finde ich Klassendiagramme etc.

Klassendiagramme haben wir bisher nur im RDD, aber wir können auch ein doc/ Ordner auf Github erstellen. Adressiert mit Issue #48.

> Wie sieht es in Sachen Sensoren aus?

Sensoren sind teil von [Meilstone_03](https://github.com/fabiansch/esep_sortingmachine/milestone/4). Zum nächstem Praktikumstermin wollen wir das allerdings schon fertig haben. Adressiert mit Issue #29 und #30 

> Haben Sie schon die Architektur für die grundlegende Kommunikation festgelegt?

Dies ist ebenfalls Teil von [Meilstone_03](https://github.com/fabiansch/esep_sortingmachine/milestone/4)  . Zum nächstem Praktikumstermin wollen wir das allerdings schon fertig haben. Adressiert mit Issue #26.

Liebe Grüße,
Fabian Schimke
