### ISSUE TITLE
implement chatter protection for SENSOR_SWITCH_IS_OPEN signal

### ISSUE THREAD

**Issue by fabiansch** [fabiansch/esep_sortingmachine#68]
when switch opens SENSOR_SWITCH_IS_OPEN chatters for 0 till x ms.
HardwareLayer should garantee that from the moment when SENSOR_SWITCH_IS_OPEN signal is triggered for the first time till (x + security) ms afterwards the signal SENSOR_SWITCH_IS_OPEN gets added to signalBuffer just once.

**Comment by maltejanssen** [comment]
done in Branch chatterProtectionSwitch

**Comment by maltejanssen** [comment]
#73
