### ISSUE TITLE
implement chatter protection for Button signals

### ISSUE THREAD

**Issue by fabiansch** [fabiansch/esep_sortingmachine#69]
when buttons get pushed BUTTON_X_PUSHED signals chatter for 0 till x ms.
HardwareLayer should garantee that from the moment when BUTTON_X_PUSHED signals are triggered for the first time till (x + security) ms afterwards the signals BUTTON_X_PUSHED gets added to signalBuffer just once.

The same for BUTTON_X_PULLED.

**Comment by maltejanssen** [comment]
done in Branch chatterProtectionSwitch
same as #68

**Comment by maltejanssen** [comment]
#73
