### ISSUE TITLE
automatitizise sensor test

### ISSUE THREAD

**Issue by fabiansch** [fabiansch/esep_sortingmachine#78]
LogicLayer::SensorTestController should work for all sensor signals:
- light barrier signal DONE
- height match signal DONE
- height measurement (send item to next cb and check height value)
- metal match signal DONE
- START_SENSOR_TEST signal DONE
- FINISH_SENSOR_TEST signal DONE

**Comment by fabiansch** [comment]
working on branch feature_serial_interface.
LogicLayer::SensorTestController already works for all light barrier signals.

**Comment by FlowwX** [comment]
merged branch
